import type { ElementSalaire } from '../elementSalaire/elementSalaire';

export const mockElementsSalaire: ElementSalaire[] = [
  {
    id: "sb",
    societeId: 1,
    variableId: 1001,
    libelle: "Salaire de base",
    type_element: "prime",
    nature: "fixe",
    imposable: true,
    soumisCnps: true,
    partEmploye: false,
    partEmployeur: true,
    prorataBase: 100,
    processCalculJson: {
      base: 1000,
      multiplicateur: 1,
      constant: 0,
    },
  },
  {
    id: "cnps",
    societeId: 1,
    variableId: 1002,
    libelle: "Cotisation CNPS",
    type_element: "retenue",
    nature: "fixe",
    imposable: false,
    soumisCnps: true,
    partEmploye: true,
    partEmployeur: true,
    prorataBase: 50,
    processCalculJson: {
      tauxEmploye: 0.04,
      tauxEmployeur: 0.08,
    },
  },
  {
    id: "irpp",
    societeId: 1,
    variableId: 1003,
    libelle: "Impôt IRPP",
    type_element: "retenue",
    nature: "variable",
    imposable: true,
    soumisCnps: false,
    partEmploye: true,
    partEmployeur: false,
    prorataBase: 25,
    processCalculJson: {
      tranches: [
        { seuil: 50000, taux: 0.1 },
        { seuil: 150000, taux: 0.15 },
        { seuil: 300000, taux: 0.2 },
      ],
    },
  },
  {
    id: "prime_perf",
    societeId: 2,
    variableId: 1004,
    libelle: "Prime de performance",
    type_element: "prime",
    nature: "variable",
    imposable: true,
    soumisCnps: true,
    partEmploye: false,
    partEmployeur: true,
    prorataBase: 60,
    processCalculJson: {
      performance: "ratio_objectif",
      multiplicateur: 1.2,
    },
  },
];
